### PR TITLE
Handle when the script fails due there is not internet connection or due an unexpected error

### LINKED ISSUE #10: Exception when there is not an internet connection
**There should be no calls to IO.inspect/1** (`lib/ex_tldr.ex`). Codacy report:
> While calls to IO.inspect might appear in some parts of production code, most calls to this function are added during debugging sessions.

To address this issue I am going to raise two different exceptions when:
  - There isn't internet connection.
  - The error is unexpected. If the error is unexpected, encourage the user to report it in this repository.

### PR DESCRIPTION
**Pull request by ivanhercaz**
This PR consists of two commits. One in which is added two exceptions in `lib/ex_tldr/exceptions.ex` and the another one in which the exceptions are applied to each case:

  1. If the script fails due there is not internet connection, raise `NoInternetConnectionError`.
  2. If the script fails due an unexpected error, raise `UnexpectedError` with the error message and encourage the user to report it on this repository.

### CODE REVIEW

**Comment by ivanhercaz** [comment]
The check that fails in this PR is the coverage test by Coveralls, because it reports a decrease of 4.2 %. The reason of this decrease are the two new conditions applied to raise the errors. I am very new performing coverage tests so I need to learn how to cover this part of the code inside tests. In addition, I have to learn how to test the condition applied when there is not internet connection.

Any idea? Either way, I will probably ask in Stack Overflow about this kind of tests before to go sleep.

CC. @owenvoke

**P.S.** I have think in the development of a mock, but I do not know how the mock could simulate a lack of internet connection.

**Comment by sbrl** [comment]
I don't know Elixr, but achieving complete code coverage with tests is all about inversion of control. If your code is sufficiently decoupled, you should be able to swap parts out for other "mock" parts.

If you haven't already, the SOLID principles are great to read up on.

**Comment by ivanhercaz** [comment]
> I don't know Elixr, but achieving complete code coverage with tests is all about inversion of control. If your code is sufficiently decoupled, you should be able to swap parts out for other "mock" parts.
> 
> If you haven't already, the SOLID principles are great to read up on.

Very interesting point. I am going to read more about it. I ask to you in Gitter because although someone does not know about one or another language, sometimes the procedural and logic, the theories, may help to address what someone wants in another language. This is the reason why I am going to read more about what you commented. Thank you very much @sbrl!

I would like to test everything before merge it. This case is a bit different, but I still have this idea. However, it may delay the development of others task.

Anyway, I already [asked in Stack Overflow](https://stackoverflow.com/questions/61808592/is-there-a-way-to-simulate-the-lack-of-internet-connection-in-an-elixir-test).

**Comment by ivanhercaz** [comment]
Well, after a [very interesting answer to the question I asked](https://stackoverflow.com/a/61811449/473597), several readings about how mocks work and how it would be possible to create a test with a mock, I finally use [Mox](https://hexdocs.pm/mox/Mox.html) for this issue (check 75fede7 although the test is commented for future reference, because now it will fails). Although I think I know how it might be address, at this moment it does not viable to apply because the methodology should be:

  - Define a [behavior](https://elixir-lang.org/getting-started/typespecs-and-behaviours.html#behaviours) for the client wrapper.
  - Then apply the behavior.

With this it would be possible to create a mock for the behavior and then test the response of the behavior and not the response of HTTPotion. At least I have in my head how it could be done, although there may be something I am not considering. Now I can not define and apply the behavior, due I will not have enough time during this week, and I do not know if I could the next week. So I propose two options:

  1. Merge this PR, although the Coveralls test failed, and open two issues for the pending tasks (one for the behavior, another for the test).
  2. Keep this PR opened and `IO.inspect` will be there until we could create a good test to cover this issue.

I prefer the first option: we change the `IO.inspect` by meaningful errors, open an issue for the behavior and another one for the test, both will require one PR each one to track fine both.

What do you think about it?

CC. @sbrl @owenvoke (I mentioned both of you because you already participated in ExTldr).

File: test/ex_tldr_test.exs [hunk 1]
```diff
@@ -58,4 +63,12 @@ defmodule ExTldrTest do
...
     assert capture_io(execute_main) =~ "Usage:"
   end
+
+  #test "should return lack of internet" do
+    # assert_raise NoInternetConnectionError,
+    #             fn ->
+    #               ClientMock
+    #               |> expect(:get, fn _ -> {:error, %HTTPoison.Error{reason: :nxdomain}} end)
+    #             end
+  #end
```
Comment (ivanhercaz) [inline test/ex_tldr_test.exs:73]: This is the test I referred in my last comment. I think that this one applied to a mock of a behavior defined for our wrapper, and not for `HTTPoison.Base`, will work (if am not wrong...).

**Comment by ivanhercaz** [comment]
I have finally decided to opt for the first option that I exposed in my last comment in this PR: merge this PR and open two new issues, one for the behavior and another one for the test.
